# Generated by Django 2.2.4 on 2019-08-05 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('synopsis', models.TextField()),
                ('classification', models.CharField(choices=[('G', 'G'), ('PG', 'PG'), ('PG-13', 'PG-13'), ('R', 'R'), ('NC-17', 'NC-17')], max_length=5)),
                ('category', models.CharField(choices=[('Acción', 'Acción'), ('Aventura', 'Aventura'), ('Comedia', 'Comedia'), ('Crimen y mafia', 'Crimen y mafia'), ('Darama', 'Darama'), ('Historia', 'Historia'), ('Horror', 'Horror'), ('Musicales', 'Musicales'), ('Ciencia ficción', 'Ciencia ficción'), ('Guerra', 'Guerra'), ('Westerns', 'Westerns')], max_length=20)),
                ('release', models.DateTimeField()),
                ('length', models.TimeField()),
            ],
        ),
    ]
