# Generated by Django 2.2.4 on 2019-08-05 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seat',
            name='handicapped',
        ),
    ]
