# Generated by Django 2.2.4 on 2019-08-05 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0002_remove_seat_handicapped'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seat',
            name='vacant',
        ),
    ]
